#!/usr/bin/env python3
"""Download the pinned open-licence fallback photos and write an attribution file.

The pins come from fallback_selection.json (or the block embedded in
docs/test-photo-set-survey.md); nothing is searched at download time, so a rerun
fetches the same photos. Standard library only.

Per photo: https download with retries and a timeout, written to a .part file and renamed
only after checks pass: JPEG/PNG header, minimum resolution from the shot list, the pinned
SHA-1 when the source publishes one, and the SHA-256 recorded in the lock file on first
download (a later change in content is reported, not accepted). Files that already pass
the checks are skipped, so reruns are idempotent.

Exit status: 0 all pinned photos present, 1 some failed (the rest are still downloaded),
2 selection unreadable, 3 --strict and fewer pins than shots.
"""
import argparse
import hashlib
import json
import os
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import imageinfo  # noqa: E402
import selection as selection_mod  # noqa: E402
import shotlist  # noqa: E402

USER_AGENT = "test-photo-set-fetch/1.0 (fallback photo download; contact: repository owner)"
MAX_BYTES = 60 * 1024 * 1024
ALLOWED_EXT = {".jpg", ".jpeg", ".png"}


class FetchError(Exception):
    pass


def local_name(pin):
    ext = os.path.splitext(urllib.parse.urlparse(pin["url"]).path)[1].lower()
    if ext not in ALLOWED_EXT:
        raise FetchError("unsupported file extension %r in %s" % (ext, pin["url"]))
    return "%s_%s%s" % (pin["slot"], pin["source"], ext)


def download(url, timeout, retries, sleep=time.sleep):
    """Return the bytes at url. Retries on network errors, 429 and 5xx with backoff."""
    last = None
    for attempt in range(retries):
        try:
            request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
            with urllib.request.urlopen(request, timeout=timeout) as response:
                data = response.read(MAX_BYTES + 1)
            if len(data) > MAX_BYTES:
                raise FetchError("file larger than %d MB" % (MAX_BYTES >> 20))
            return data
        except urllib.error.HTTPError as exc:
            last = "HTTP %d" % exc.code
            if exc.code not in (429, 500, 502, 503, 504):
                break  # 404 and friends: the URL changed or is gone, retrying will not help
        except (urllib.error.URLError, TimeoutError, ConnectionError, OSError) as exc:
            last = str(getattr(exc, "reason", exc))
        if attempt + 1 < retries:
            sleep(2 ** attempt * 2)
    raise FetchError("download failed after %d attempt(s): %s" % (attempt + 1, last))


def check_content(data, pin, limits, lock, name):
    """Raise FetchError unless the bytes match the pin. Returns the sha256."""
    try:
        info = imageinfo.inspect_bytes(data)
    except imageinfo.ImageError as exc:
        raise FetchError("not a usable image (%s); the URL may now serve a different page" % exc)
    if info.long_edge < limits["min_long_edge_px"] or info.short_edge < limits["min_short_edge_px"]:
        raise FetchError("%dx%d is below the minimum resolution" % (info.width, info.height))
    if pin.get("sha1") and hashlib.sha1(data).hexdigest() != pin["sha1"].lower():
        raise FetchError("SHA-1 differs from the pinned value (file replaced upstream)")
    digest = hashlib.sha256(data).hexdigest()
    if name in lock and lock[name] != digest:
        raise FetchError("SHA-256 differs from the lock file (content changed since first download)")
    return digest


def attribution_text(pins_ok, as_of_note):
    lines = ["Attribution for fallback photos (generated by fetch_fallback.py)", as_of_note, ""]
    for pin, name in pins_ok:
        lines.append("%s  %s" % (name, pin["attribution"]))
        lines.append("    source: %s | page: %s | licence: %s %s" % (
            pin["source"], pin["page_url"], pin["license"], pin["license_url"]))
    lines.append("")
    lines.append("CC0 and public-domain photos need no credit; the lines above are courtesy and provenance.")
    lines.append("Licences do not cover the rights of people shown: see docs/test-photo-set-survey.md, Rights risks.")
    return "\n".join(lines) + "\n"


def write_atomic(path, data):
    tmp = path + ".part"
    with open(tmp, "wb") as handle:
        handle.write(data)
    os.replace(tmp, path)


def run(selection, out_dir, lock_path, limits, expected, timeout=30, retries=3, pause=1.0,
        sleep=time.sleep, log=print):
    """Fetch every pin. Returns (ok_count, failures dict slot->reason)."""
    os.makedirs(out_dir, exist_ok=True)
    lock = {}
    if os.path.isfile(lock_path):
        with open(lock_path, encoding="utf-8") as handle:
            lock = json.load(handle)
    lock_changed = False
    done, failures = [], {}
    for pin in selection["pins"]:
        slot = pin["slot"]
        try:
            name = local_name(pin)
            target = os.path.join(out_dir, name)
            existing = None
            if os.path.isfile(target):
                with open(target, "rb") as handle:
                    existing = handle.read()
                try:
                    check_content(existing, pin, limits, lock, name)
                    log("[%s] %s already present and verified, skipped" % (slot, name))
                    done.append((pin, name))
                    continue
                except FetchError as exc:
                    log("[%s] %s present but invalid (%s); downloading again" % (slot, name, exc))
            data = download(pin["url"], timeout, retries, sleep)
            digest = check_content(data, pin, limits, lock, name)
            write_atomic(target, data)
            if lock.get(name) != digest:
                lock[name] = digest
                lock_changed = True
            log("[%s] %s downloaded (%d bytes, sha256 %s)" % (slot, name, len(data), digest[:12]))
            done.append((pin, name))
            sleep(pause)
        except FetchError as exc:
            failures[slot] = str(exc)
            log("[%s] FAILED: %s" % (slot, exc))
        except OSError as exc:
            failures[slot] = "file error: %s" % exc
            log("[%s] FAILED: file error: %s" % (slot, exc))
    if lock_changed:
        write_atomic(lock_path, (json.dumps(lock, indent=2, sort_keys=True) + "\n").encode())
    note = "As of %s selection; %d of %d shots covered by pins; %d downloaded and verified." % (
        selection.get("as_of", "unknown date"), len(selection["pins"]), expected, len(done))
    write_atomic(os.path.join(out_dir, "ATTRIBUTION.txt"), attribution_text(done, note).encode("utf-8"))
    return len(done), failures


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--selection", help="pins file (.json, or the survey .md); default: auto")
    parser.add_argument("--out-dir", default="photos/fallback")
    parser.add_argument("--lock", default=selection_mod.DEFAULT_LOCK,
                        help="SHA-256 lock file recorded on first download")
    parser.add_argument("--timeout", type=int, default=30)
    parser.add_argument("--retries", type=int, default=3)
    parser.add_argument("--strict", action="store_true", help="fail if any shot has no pin")
    args = parser.parse_args(argv)
    path = args.selection or selection_mod.find_existing()
    try:
        if not path:
            raise selection_mod.SelectionError(
                "no selection found; run survey.py first or pass --selection")
        selection = selection_mod.load_selection(path)
        shot_list = shotlist.load_shot_list()
    except (selection_mod.SelectionError, ValueError, OSError) as exc:
        print("cannot start: %s" % exc, file=sys.stderr)
        return 2
    expected = len(shot_list["shots"])
    covered = {pin["slot"] for pin in selection["pins"]}
    gaps = [s["id"] for s in shot_list["shots"] if s["id"] not in covered]
    print("Selection: %s (%d pins, as of %s)" % (path, len(selection["pins"]), selection.get("as_of")))
    if gaps:
        print("No pin for: %s" % ", ".join(gaps))
    ok, failures = run(selection, args.out_dir, args.lock, shot_list["resolution"], expected,
                       args.timeout, args.retries)
    print("%d of %d pinned photos present in %s; attribution in %s" % (
        ok, len(selection["pins"]), args.out_dir, os.path.join(args.out_dir, "ATTRIBUTION.txt")))
    if failures:
        print("Failed slots: " + ", ".join("%s (%s)" % kv for kv in sorted(failures.items())))
        return 1
    return 3 if (gaps and args.strict) else 0


if __name__ == "__main__":
    sys.exit(main())
